services:
  manager-backend:
    image: test_image:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8083"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/postgres
  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:80"  # Было "8081:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:8080/v3/api-docs
volumes:
  db-data:
  pgadmin-data: